Repository LaughLog/laugh-log, pull requests merged in 2024-03, with the labels that each got.

#26 [#25] 랜딩 페이지 헤더 로그인 로그아웃 버튼 추가
  client/app/(auth)/sign-in/[[...sign-in]]/page.tsx
  client/app/(home)/_components/_bannerComponents/header.tsx
  client/components/auth/customSignIn.tsx
  client/components/auth/customSignOut.tsx
Labels: feat

#23 [#22] 템플릿으로 시작하기 마크업 완료
  client/app/(dashboard)/(routes)/dashboard/[user-id]/page.tsx
  client/app/(dashboard)/_components/mainContainer.tsx
  client/app/(dashboard)/_components/startTemplate.tsx
  client/app/(dashboard)/_components/teamBoard.tsx
  client/app/(dashboard)/_components/templateItem.tsx
  client/app/(home)/(routes)/page.tsx
  client/app/(home)/_components/bannerSection.tsx
  client/middleware.ts
  client/package-lock.json
  client/package.json
  client/public/new-board.svg
Labels: design

#29 [#28] 대시보드 사이드바 구현
  client/app/(dashboard)/(routes)/dashboard/[user-id]/page.tsx
  client/app/(dashboard)/(routes)/dashboard/layout.tsx
  client/app/(dashboard)/(routes)/dashboard/page.tsx
  client/app/(dashboard)/_components/sidebar/sidebar.css
  client/app/(dashboard)/_components/sidebar/sidebar.tsx
  client/app/layout.tsx
  client/package-lock.json
  client/public/logo.svg
  client/public/sidebar-arrow.svg
  client/public/star.svg
  client/types/dashboard.ts
Labels: feat, design

#30 [#24] 툴박스 마크업 및 선택 기능 구현
  client/.gitignore
  client/app/(whiteboard)/(routes)/whiteboard/page.tsx
  client/app/(whiteboard)/_component/_toolbar-component/PostIt.tsx
  client/app/(whiteboard)/_component/_toolbar-component/main-tool-container.tsx
  client/app/(whiteboard)/_component/_toolbar-component/stickers.tsx
  client/app/(whiteboard)/_component/toolbar.tsx
  client/app/globals.css
  client/constants/.gitkeep
  client/constants/toolbar.ts
  client/middleware.ts
  client/package-lock.json
  client/package.json
Labels: design

#33 [#32] 대시보드 팀 보드 마크업
  client/app/(dashboard)/(routes)/dashboard/layout.tsx
  client/app/(dashboard)/(routes)/dashboard/page.tsx
  client/app/(dashboard)/_components/boardItem.tsx
  client/app/(dashboard)/_components/boardList.tsx
  client/app/(dashboard)/_components/boardMenu.tsx
  client/app/(dashboard)/_components/emptyBoards.tsx
  client/app/(dashboard)/_components/mainContainer.tsx
  client/app/(dashboard)/_components/startWithTemplate.tsx
  client/app/(dashboard)/_components/teamBoard.tsx
  client/components/ui/dropdown-menu.tsx
  client/package-lock.json
  client/package.json
  client/public/board-more.svg
  client/types/dashboard.ts
Labels: design

#35 [#34] 대시보드 파이어베이스 연동
  client/app/(dashboard)/(routes)/dashboard/page.tsx
  client/app/(dashboard)/_components/MenuItem.tsx
  client/app/(dashboard)/_components/boardItem.tsx
  client/app/(dashboard)/_components/boardList.tsx
  client/app/(dashboard)/_components/boardMenu.tsx
  client/app/(dashboard)/_components/emptyBoards.tsx
  client/app/(dashboard)/_components/startWithTemplate.tsx
  client/app/(dashboard)/_components/teamBoard.tsx
  client/app/(dashboard)/_components/templateItem.tsx
  client/components/ui/alert-dialog.tsx
  client/components/ui/input.tsx
  client/lib/firebaseUtils.ts
  client/package-lock.json
  client/package.json
  client/types/dashboard.ts
Labels: feat

#36 [#27] 텍스트 에디터 블럭 생성하기 기능 구현 (socket 연결 전)
  client/app/(textEditor)/(routes)/text-editor/page.tsx
  client/app/(textEditor)/_components/editableBlock.tsx
  client/app/(textEditor)/_components/editablePage.tsx
  client/lib/utils.ts
  client/package-lock.json
  client/package.json
  client/types/textEditor.ts
Labels: feat

#39 [#37] 텍스트 에디터 블럭 삭제하기 기능 구현 (socket 연결 전)
  client/app/(textEditor)/_components/editableBlock.tsx
  client/app/(textEditor)/_components/editablePage.tsx
  client/types/textEditor.ts
Labels: feat
