Repository LaughLog/laugh-log, pull requests merged in 2024-02, with the labels that each got.

#9 [#1] feat: 글로벌 스타일 설정
  client/.prettierrc.json
  client/app/(home)/(routes)/page.tsx
  client/app/globals.css
  client/app/layout.tsx
  client/package-lock.json
  client/package.json
  client/postcss.config.js
  client/tailwind.config.ts
Labels: env

#14 [#12] 초기 세팅 개선
  .github/workflows/preview.yml
  client/app/(chat)/(routes)/chat/page.tsx
  client/app/(chat)/_components/ChatBox.tsx
  client/app/(chat)/_components/ChatContainer.tsx
  client/app/(chat)/_components/ChatList.tsx
  client/app/(chat)/_components/InputText.tsx
  client/app/(chat)/_components/UserLogin.tsx
  client/app/layout.tsx
  client/public/.gitkeep
  client/public/next.svg
  client/public/vercel.svg
Labels: modify

#16 [#15] 로그인/회원가입 페이지 기능 구현 및 마크업
  client/app/(auth)/sign-in/[[...sign-in]]/page.tsx
  client/app/(auth)/sign-in/[[...sign-in]]/sign-in.css
  client/app/layout.tsx
  client/components/auth/custom-sign-in-button.tsx
  client/components/auth/custom-sign-out-button.tsx
  client/middleware.ts
  client/package-lock.json
  client/package.json
  client/public/.gitkeep
  client/public/sign-in-bg.svg
  client/public/sign-in-welcome.svg
  client/tailwind.config.ts
Labels: feat

#18 [#17] 리액트 쿼리 provider 세팅
  client/app/layout.tsx
  client/package-lock.json
  client/package.json
  client/provider/react-query-provider.tsx
Labels: init

#19 [#11] 랜딩 페이지 마크업 작업 완료
  client/app/(auth)/sign-in/[[...sign-in]]/page.tsx
  client/app/(dashboard)/(routes)/dashboard/[user-id]/page.tsx
  client/app/(dashboard)/_components/main.tsx
  client/app/(dashboard)/_components/startTemplate.tsx
  client/app/(dashboard)/_components/subtitle.tsx
  client/app/(dashboard)/_components/teamBoard.tsx
  client/app/(dashboard)/_components/templateItem.tsx
  client/app/(home)/(routes)/page.tsx
  client/app/(home)/_components/.gitkeep
  client/app/(home)/_components/_bannerComponents/banner.tsx
  client/app/(home)/_components/_bannerComponents/header.tsx
  client/app/(home)/_components/_footerComponents/footerText.tsx
  client/app/(home)/_components/bannerSection.tsx
  client/app/(home)/_components/bodySection.tsx
  client/app/(home)/_components/footerSection.tsx
  client/app/globals.css
  client/components/ui/text-hint.tsx
  client/constants/.gitkeep
  client/hook/useInnerWidth.ts
  client/hook/useRectOnTop.ts
  client/package-lock.json
  client/package.json
  client/public/desc-image1.png
  client/public/lines.png
  client/public/lines2.svg
  client/public/main-text.svg
  client/public/no-bg-star.png
  client/public/pointing-hand.png
  client/public/star.png
  client/public/tomato-sticker.png
  client/tailwind.config.ts
Labels: design
